{"id": "CVE-2020-26213", "sourceIdentifier": "security-advisories@github.com", "published": "2020-11-06T17:15:12.280", "lastModified": "2020-11-17T17:11:57.533", "vulnStatus": "Analyzed", "cveTags": [], "descriptions": [{"lang": "en", "value": "In teler before version 0.0.1, if you run teler inside a Docker container and encounter `errors.Exit` function, it will cause denial-of-service (`SIGSEGV`) because it doesn't get process ID and process group ID of teler properly to kills. The issue is patched in teler 0.0.1 and 0.0.1-dev5.1."}, {"lang": "es", "value": "En teler versiones anteriores a 0.0.1, si ejecuta teler dentro de un contenedor Docker y encuentra la funci\u00f3n \"errors.Exit\", causar\u00e1 una denegaci\u00f3n de servicio (\"SIGSEGV\") porque no obtiene el ID del proceso y el ID del grupo de procesos de teler apropiadamente para eliminar.&#xa0;El problema est\u00e1 parcheado en teler 0.0.1 y 0.0.1-dev5.1"}], "metrics": {"cvssMetricV31": [{"source": "nvd@nist.gov", "type": "Primary", "cvssData": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "NONE", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "NONE", "integrityImpact": "NONE", "availabilityImpact": "HIGH", "baseScore": 7.5, "baseSeverity": "HIGH"}, "exploitabilityScore": 3.9, "impactScore": 3.6}, {"source": "security-advisories@github.com", "type": "Secondary", "cvssData": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H", "attackVector": "NETWORK", "attackComplexity": "HIGH", "privilegesRequired": "NONE", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "NONE", "integrityImpact": "NONE", "availabilityImpact": "HIGH", "baseScore": 5.9, "baseSeverity": "MEDIUM"}, "exploitabilityScore": 2.2, "impactScore": 3.6}], "cvssMetricV2": [{"source": "nvd@nist.gov", "type": "Primary", "cvssData": {"version": "2.0", "vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P", "accessVector": "NETWORK", "accessComplexity": "LOW", "authentication": "NONE", "confidentialityImpact": "NONE", "integrityImpact": "NONE", "availabilityImpact": "PARTIAL", "baseScore": 5.0}, "baseSeverity": "MEDIUM", "exploitabilityScore": 10.0, "impactScore": 2.9, "acInsufInfo": false, "obtainAllPrivilege": false, "obtainUserPrivilege": false, "obtainOtherPrivilege": false, "userInteractionRequired": false}]}, "weaknesses": [{"source": "security-advisories@github.com", "type": "Primary", "description": [{"lang": "en", "value": "CWE-476"}]}], "configurations": [{"nodes": [{"operator": "OR", "negate": false, "cpeMatch": [{"vulnerable": true, "criteria": "cpe:2.3:a:teler_project:teler:*:*:*:*:*:*:*:*", "versionEndExcluding": "0.0.1", "matchCriteriaId": "B8E18AB1-AE1F-4989-934B-6F1006A11561"}]}]}], "references": [{"url": "https://github.com/kitabisa/teler/commit/ec6082049dba9e44a21f35fb7b123d42ce1a1a7e", "source": "security-advisories@github.com", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://github.com/kitabisa/teler/security/advisories/GHSA-jhj6-5mh6-4pvf", "source": "security-advisories@github.com", "tags": ["Third Party Advisory"]}], "techniques": [{"techniqueID": "TA0010", "comment": "CVE-2020-26213 - A denial-of-service vulnerability in teler allows an attacker to crash the service, which can lead to unavailability of the service and subsequent attacks."}, {"techniqueID": "TA0040", "comment": "CVE-2020-26213 - A failure to properly handle errors in teler can lead to a denial-of-service attack, which can be exploited by an attacker to crash the service."}, {"techniqueID": "TA0005", "comment": "CVE-2020-26213 - A vulnerability in teler allows an attacker to cause a denial-of-service attack, which can lead to unavailability of the service and subsequent attacks."}], "stix_bundle": {"id": "https://example.com/stix_bundle.json", "type": "stixbundle", "description": "STIX Bundle for CVE-2020-26213", "created_by_ref": "https://example.com/user", "modified": "2021-01-01T00:00:00.000Z", "objects": [{"type": "vulnerability", "id": "https://example.com/cve-2020-26213", "name": "CVE-2020-26213", "description": "A denial-of-service vulnerability in teler"}, {"type": "indicator", "id": "https://example.com/indicator-1", "name": "Teler Denial-of-Service Attack", "description": "An attacker crashes the teler service"}, {"type": "course-of-action", "id": "https://example.com/course-of-action-1", "name": "Patch Teler", "description": "Patch teler to version 0.0.1 or later", "related_sidelocks": [{"rel_type": "Mitigates", "target_ref": "https://example.com/cve-2020-26213"}]}, {"type": "course-of-action", "id": "https://example.com/course-of-action-2", "name": "Monitor for Denial-of-Service Attacks", "description": "Monitor for denial-of-service attacks and alert on crashes", "related_sidelocks": [{"rel_type": "Detects", "target_ref": "https://example.com/indicator-1"}]}], "relationships": [{"source_ref": "https://example.com/cve-2020-26213", "destination_ref": "https://example.com/indicator-1", "type": "indicates"}]}, "technical_analysis": {"Introduction": "The CVE-2020-26213 vulnerability is a denial-of-service vulnerability in teler that allows an attacker to crash the service.", "Impact and Scope": "The vulnerability is rated high-severity and has a CVSS score of 7.5. It can lead to unavailability of the service and subsequent attacks.", "Related MITRE ATT&CK Techniques": "The vulnerability is related to MITRE ATT&CK techniques TA0010, TA0040, and TA0005.", "Technical Details": "The vulnerability is due to a failure to properly handle errors in teler, which can lead to a denial-of-service attack.", "Detection": "The vulnerability can be detected by monitoring for denial-of-service attacks and alerting on crashes.", "Mitigation": "The vulnerability can be mitigated by patching teler to version 0.0.1 or later.", "Conclusion": "The CVE-2020-26213 vulnerability is a high-severity denial-of-service vulnerability in teler that can lead to unavailability of the service and subsequent attacks."}, "executive_analysis": {"Overview": "The CVE-2020-26213 vulnerability is a denial-of-service vulnerability in teler that can lead to unavailability of the service and subsequent attacks.", "Business Impact": "The vulnerability can lead to financial loss and reputational damage due to the unavailability of the service.", "Technical Impact": "The vulnerability can lead to a loss of control over the service and subsequent attacks.", "Mitigation Strategies": "The vulnerability can be mitigated by patching teler to version 0.0.1 or later and monitoring for denial-of-service attacks.", "Recommendations": "Executives should prioritize patching teler to version 0.0.1 or later and implementing monitoring for denial-of-service attacks.", "Conclusions": "The CVE-2020-26213 vulnerability is a high-severity denial-of-service vulnerability in teler that requires immediate attention and mitigation."}}